version: '3'
services:
  database:
    image: 'mongo'
    container_name: 'resto-mongo-container'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE='resto'
    volumes:
      - ./mongodb/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./mongodb/db:/data/db
    ports:
      - '27017-27019:27017-27019'